import { Injectable, Logger } from '@nestjs/common';
// eslint-disable-next-line @typescript-eslint/no-var-requires
const pdfmake = require('pdfmake');
import type { TDocumentDefinitions, Content, TableCell, StyleDictionary } from 'pdfmake/interfaces';

interface ReportSection {
  title: string;
  content: string;
  level: number;
}

interface PdfRequest {
  title: string;
  projectDomain: string;
  reportType: string;
  generatedAt: string;
  sections: ReportSection[];
  metadata: Record<string, string>;
}

interface PdfResult {
  pdfBase64: string;
  pageCount: number;
  fileSizeBytes: number;
}

const BRAND_COLOR = '#E11D48';
const DARK_TEXT = '#18181B';
const MUTED_TEXT = '#71717A';
const BORDER_COLOR = '#E4E4E7';

@Injectable()
export class PdfGeneratorService {
  private readonly logger = new Logger(PdfGeneratorService.name);

  constructor() {
    pdfmake.fonts = {
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique',
      },
    };
  }

  async generate(request: PdfRequest): Promise<PdfResult> {
    const docDefinition = this.buildDocument(request);
    const pdfBuffer = await this.createPdfBuffer(docDefinition);

    const base64 = pdfBuffer.toString('base64');
    const pageCount = this.estimatePageCount(pdfBuffer);

    return {
      pdfBase64: base64,
      pageCount,
      fileSizeBytes: pdfBuffer.length,
    };
  }

  private buildDocument(request: PdfRequest): TDocumentDefinitions {
    const content: Content[] = [];

    // Title page
    content.push({ text: '', margin: [0, 80, 0, 0] } as Content);
    content.push({ text: request.title, style: 'reportTitle' } as Content);
    content.push({
      text: `${request.projectDomain} · ${request.reportType.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase())}`,
      style: 'subtitle',
    } as Content);
    content.push({ text: `Generated: ${request.generatedAt.slice(0, 10)}`, style: 'subtitle' } as Content);
    content.push({ canvas: [{ type: 'line', x1: 0, y1: 10, x2: 200, y2: 10, lineWidth: 2, lineColor: BRAND_COLOR }], margin: [0, 20, 0, 10] } as Content);

    // Metadata table
    if (request.metadata && Object.keys(request.metadata).length > 0) {
      const metaRows: TableCell[][] = [
        [
          { text: 'Property', style: 'tableHeader' },
          { text: 'Value', style: 'tableHeader' },
        ],
      ];
      for (const [key, value] of Object.entries(request.metadata)) {
        if (value) {
          metaRows.push([
            { text: key.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase()), style: 'tableCell' },
            { text: value, style: 'tableCell' },
          ]);
        }
      }
      content.push({
        table: { headerRows: 1, widths: ['*', '*'], body: metaRows },
        layout: this.getTableLayout(),
        margin: [0, 10, 0, 20],
      } as Content);
    }

    content.push({ text: '', pageBreak: 'after' } as Content);

    // Sections
    for (const section of request.sections) {
      const headingStyle = section.level === 1 ? 'sectionH1' : section.level === 2 ? 'sectionH2' : 'sectionH3';
      content.push({ text: section.title, style: headingStyle } as Content);

      const sectionContent = this.parseMarkdownContent(section.content);
      content.push(...sectionContent);
      content.push({ text: '', margin: [0, 8, 0, 0] } as Content);
    }

    return {
      content,
      defaultStyle: { font: 'Helvetica', fontSize: 10, color: DARK_TEXT },
      styles: this.getStyles(),
      pageSize: 'A4',
      pageMargins: [71, 71, 71, 71], // ~25mm
      footer: (currentPage: number, pageCount: number) => ({
        text: `Page ${currentPage} of ${pageCount} — Generated by Pulse OS`,
        alignment: 'center',
        fontSize: 8,
        color: MUTED_TEXT,
        margin: [0, 20, 0, 0],
      }),
    };
  }

  private parseMarkdownContent(text: string): Content[] {
    const content: Content[] = [];
    const lines = text.split('\n');
    let i = 0;

    while (i < lines.length) {
      const line = lines[i].trim();

      if (!line) {
        i++;
        continue;
      }

      // Horizontal rule
      if (line === '---' || line === '***' || line === '___') {
        content.push({ canvas: [{ type: 'line', x1: 0, y1: 0, x2: 515, y2: 0, lineWidth: 0.5, lineColor: BORDER_COLOR }], margin: [0, 6, 0, 6] } as Content);
        i++;
        continue;
      }

      // Table
      if (line.startsWith('|') && line.includes('|')) {
        const tableRows: string[][] = [];
        while (i < lines.length && lines[i].trim().startsWith('|')) {
          const raw = lines[i].trim();
          if (/^\|[\s\-:|]+\|$/.test(raw)) {
            i++;
            continue;
          }
          const cells = raw.split('|').slice(1, -1).map((c) => c.trim());
          tableRows.push(cells);
          i++;
        }
        if (tableRows.length > 0) {
          content.push(this.buildTable(tableRows));
          content.push({ text: '', margin: [0, 8, 0, 0] } as Content);
        }
        continue;
      }

      // Bullet list
      if (line.startsWith('- ') || line.startsWith('* ')) {
        content.push({ text: `• ${line.slice(2)}`, style: 'bodyText', margin: [10, 0, 0, 4] } as Content);
        i++;
        continue;
      }

      // Numbered list
      const numMatch = line.match(/^(\d+)\.\s+(.*)/);
      if (numMatch) {
        content.push({ text: `${numMatch[1]}. ${numMatch[2]}`, style: 'bodyText', margin: [10, 0, 0, 4] } as Content);
        i++;
        continue;
      }

      // Regular paragraph with bold support
      const formatted = this.formatInlineMarkdown(line);
      content.push({ text: formatted, style: 'bodyText' } as Content);
      i++;
    }

    return content;
  }

  private formatInlineMarkdown(text: string): Content {
    // Split by bold markers **...**
    const parts: Array<{ text: string; bold?: boolean }> = [];
    const regex = /\*\*(.+?)\*\*/g;
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = regex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        parts.push({ text: text.slice(lastIndex, match.index) });
      }
      parts.push({ text: match[1], bold: true });
      lastIndex = regex.lastIndex;
    }
    if (lastIndex < text.length) {
      parts.push({ text: text.slice(lastIndex) });
    }

    if (parts.length === 1 && !parts[0].bold) {
      return parts[0].text as unknown as Content;
    }
    return parts as unknown as Content;
  }

  private buildTable(rows: string[][]): Content {
    if (rows.length === 0) return { text: '' } as Content;

    const colCount = rows[0].length;
    const widths = Array(colCount).fill('*');

    const body: TableCell[][] = rows.map((row, rowIndex) =>
      row.map((cell) => ({
        text: cell,
        style: rowIndex === 0 ? 'tableHeader' : 'tableCell',
      })),
    );

    return {
      table: { headerRows: 1, widths, body },
      layout: this.getTableLayout(),
      margin: [0, 4, 0, 4],
    } as Content;
  }

  private getTableLayout() {
    return {
      hLineWidth: () => 0.5,
      vLineWidth: () => 0.5,
      hLineColor: () => BORDER_COLOR,
      vLineColor: () => BORDER_COLOR,
      paddingLeft: () => 8,
      paddingRight: () => 8,
      paddingTop: () => 6,
      paddingBottom: () => 6,
      fillColor: (rowIndex: number) => {
        if (rowIndex === 0) return BRAND_COLOR;
        return rowIndex % 2 === 0 ? '#FAFAFA' : null;
      },
    };
  }

  private getStyles(): StyleDictionary {
    return {
      reportTitle: { fontSize: 24, bold: true, color: DARK_TEXT, margin: [0, 0, 0, 6] },
      subtitle: { fontSize: 11, color: MUTED_TEXT, margin: [0, 0, 0, 4] },
      sectionH1: { fontSize: 18, bold: true, color: DARK_TEXT, margin: [0, 20, 0, 10] },
      sectionH2: { fontSize: 14, bold: true, color: DARK_TEXT, margin: [0, 14, 0, 8] },
      sectionH3: { fontSize: 12, bold: true, color: DARK_TEXT, margin: [0, 10, 0, 6] },
      bodyText: { fontSize: 10, color: DARK_TEXT, lineHeight: 1.4, margin: [0, 0, 0, 8] },
      tableHeader: { fontSize: 9, bold: true, color: '#FFFFFF' },
      tableCell: { fontSize: 9, color: DARK_TEXT },
    };
  }

  private async createPdfBuffer(docDefinition: TDocumentDefinitions): Promise<Buffer> {
    const doc = pdfmake.createPdf(docDefinition);
    return doc.getBuffer();
  }

  private estimatePageCount(buffer: Buffer): number {
    // Count PDF page objects
    const content = buffer.toString('binary');
    const matches = content.match(/\/Type\s*\/Page[^s]/g);
    return matches ? matches.length : 1;
  }
}
