import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

interface DeliveryPayload {
  channel: string;
  target: string;
  workflowName: string;
  agentResponse: string;
  recommendations: Array<{ title: string; rationale: string; action?: string }>;
}

@Injectable()
export class DeliveryService {
  private readonly logger = new Logger(DeliveryService.name);

  constructor(private readonly configService: ConfigService) {}

  async deliver(payload: DeliveryPayload): Promise<void> {
    switch (payload.channel) {
      case 'slack':
        return this.deliverSlack(payload);
      case 'email':
        return this.deliverEmail(payload);
      default:
        throw new Error(`Unknown delivery channel: ${payload.channel}`);
    }
  }

  private async deliverSlack(payload: DeliveryPayload): Promise<void> {
    const webhookUrl = payload.target;

    // Validate webhook URL — use hostname comparison to prevent SSRF via
    // URLs like https://hooks.slack.com.attacker.com/...
    let parsedWebhookUrl: URL;
    try {
      parsedWebhookUrl = new URL(webhookUrl);
    } catch {
      throw new Error('Invalid Slack webhook URL');
    }
    if (parsedWebhookUrl.protocol !== 'https:' || parsedWebhookUrl.hostname !== 'hooks.slack.com') {
      throw new Error('Invalid Slack webhook URL');
    }

    const blocks = [
      {
        type: 'header',
        text: { type: 'plain_text', text: `📊 ${payload.workflowName}` },
      },
      {
        type: 'section',
        text: { type: 'mrkdwn', text: payload.agentResponse.slice(0, 2900) },
      },
    ];

    if (payload.recommendations.length > 0) {
      blocks.push({
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: '*Recommendations:*\n' +
            payload.recommendations
              .slice(0, 5)
              .map((r, i) => `${i + 1}. *${r.title}* — ${r.rationale}`)
              .join('\n'),
        },
      });
    }

    const response = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ blocks }),
    });

    if (!response.ok) {
      throw new Error(`Slack delivery failed: ${response.status} ${response.statusText}`);
    }

    this.logger.log(`Delivered to Slack: ${payload.workflowName}`);
  }

  private async deliverEmail(payload: DeliveryPayload): Promise<void> {
    const sendgridApiKey = this.configService.get<string>('SENDGRID_API_KEY');
    const fromEmail = this.configService.get<string>('EMAIL_FROM') ?? 'notifications@rankorganiq.com';

    if (!sendgridApiKey) {
      this.logger.warn('SENDGRID_API_KEY not configured, skipping email delivery');
      return;
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(payload.target)) {
      throw new Error('Invalid email address for delivery target');
    }

    const htmlContent = this.buildEmailHtml(payload);

    const response = await fetch('https://api.sendgrid.com/v3/mail/send', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${sendgridApiKey}`,
      },
      body: JSON.stringify({
        personalizations: [{ to: [{ email: payload.target }] }],
        from: { email: fromEmail, name: 'Pulse OS' },
        subject: `[Pulse] ${payload.workflowName}`,
        content: [{ type: 'text/html', value: htmlContent }],
      }),
    });

    if (!response.ok) {
      throw new Error(`Email delivery failed: ${response.status} ${response.statusText}`);
    }

    this.logger.log(`Delivered email to ${payload.target}: ${payload.workflowName}`);
  }

  private buildEmailHtml(payload: DeliveryPayload): string {
    const recsHtml = payload.recommendations.length > 0
      ? `<h3>Recommendations</h3><ol>${payload.recommendations
          .map((r) => `<li><strong>${this.escapeHtml(r.title)}</strong> — ${this.escapeHtml(r.rationale)}</li>`)
          .join('')}</ol>`
      : '';

    return `
      <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto;">
        <h2 style="color: #1a1a2e;">📊 ${this.escapeHtml(payload.workflowName)}</h2>
        <div style="white-space: pre-wrap; line-height: 1.6;">${this.escapeHtml(payload.agentResponse)}</div>
        ${recsHtml}
        <hr style="margin-top: 24px; border: none; border-top: 1px solid #e0e0e0;" />
        <p style="font-size: 12px; color: #888;">This report was generated by Pulse OS.</p>
      </div>
    `;
  }

  private escapeHtml(str: string): string {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
